name: Upload assets to s3
on: [push]
jobs:
  upload-dev-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: aws s3 cp ui s3://org.haitianrelief.dev --recursive
