name: Upload assets to s3
on: [push]
jobs:
  staging:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: (cd cdk && npm i && STAGE=staging npx cdk deploy)
      - run: aws s3 cp ui s3://org.haitianrelief.dev --recursive
